name: CI/CD

# Controls when the workflow will run
on:
  # Activates the workflow; then there is a push to the main or master branch
  push:
    branches: [main, master]

  # allows you to manually execute this pipeline from the Actions tab.
  workflow_dispatch:

# A workflow run consists of one or more jobs that can be executed either sequentially or concurrently.
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    #
    steps:
      - uses: actions/checkout@v3  
      - uses: actions/setup-python@v3  
      - run: pip install -r requirements.txt  # install requirements to enable GitHub run tests

      - uses: akhileshns/heroku-deploy@v3.12.12 #
        with:
          heroku_api_key: 1debf9bb-7191-49a3-8dff-41a4d932f4d5
          heroku_app_name: planx-preview
          heroku_email: nguyenviet3057@gmail.com